#!/bin/bash

# Copyright 2018 Bang & Olufsen A/S
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Resets the ADAU1451 DSP and allows it to self-boot (if enabled).
# Also holds the mute pin high and plays a sound to "prime" the I2S link – not sure if required on v1.0 boards.
# Requires wiringpi to be installed.
echo "SigmaDSP Reset (c) 2018 Bang & Olufsen A/S"
gpio mode 2 out
gpio write 2 1 # mute
gpio mode 0 out
gpio write 0 0; sleep 1; gpio write 0 1  # reset
gpio mode 0 in # disable reset pin
sleep 5
#gpio mode 10 out # SS/ADDR0, these interfere with the SPI link so disabled for now
#for run in {1..3}
#do
#  gpio write 10 1 # enable SPI slave mode
#  gpio write 10 0
#done
#gpio mode 10 in # SS/ADDR0
aplay -q /home/pi/Music/setup-required.wav
gpio write 2 0 # unmute
gpio mode 2 in # disable mute pin
echo "Reset done."
